
import Footer from "@/components/Footer";
import { Header } from "@/components/Header";
import ThemedBody from "@/components/ThemedBody";
import Topbar from "@/components/Topbar";
import "./globals.css";
import Provider from "./Provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <Provider>
          <ThemedBody>
            <Topbar />
            <Header />
            <main className ='flex-grow '>
              {children}
            </main>
            <Footer />
            </ThemedBody>
    </Provider>
      </html>
  );
}


